invoicing/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import MakeOrderView, InvoiceView, InvoiceListView, UsersView, CreateUserView, ListProductsView
from rest_framework.authtoken import views
urlpatterns = [
  url(r'^invoice/$', InvoiceListView.as_view()),
  url(r'invoice/(?P<id>\d+)/$', InvoiceView.as_view()),
  url(r'users/$', UsersView.as_view()),
  url(r'users/create$', CreateUserView.as_view()),
  url(r'company/(?P<company_id>\d+)/products$', ListProductsView.as_view()),
  url(r'orders/create', MakeOrderView.as_view()),
]

urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token)
]
urlpatterns = format_suffix_patterns(urlpatterns)

invoicing/invoicing/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import index


#delete on going live
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Pastebin API')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('invoice/', include('invoice.urls')),
    path('', index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('company/', include('company.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^docs/', schema_view),
    path('api/', include("api.urls")),
    path('products/', include("products.urls")),
    path('orders/', include("orders.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



#delete when going to prod, static files have to be served on media server, memcached


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

from django.conf.urls import handler400, handler403, handler404, handler500


handler400 = 'invoicing.views.bad_request'
handler403 = 'invoicing.views.permission_denied'
handler404 = 'invoicing.views.page_not_found'
handler500 = 'invoicing.views.server_error'

invoicing/products/urls.py
from django.urls import path
from .views import AddProductView, ProductCategoryEditView, ProductCategoryView, ProductsListView
urlpatterns = [
    path("category/", ProductCategoryView.as_view(), name="product_category"),
    path("category/add", ProductCategoryEditView.as_view(), name="add_product_category"),
    path("", ProductsListView.as_view(), name="product_list"),
    path("add/", AddProductView.as_view(), name="add_product"),
    #path("products/", ProfileView.as_view(), name="profile_view"),
    #path("products/add", CompanyEditView.as_view(), name='company_edit')
]

invoicing/products/models.py
#from django_mysql import models as mysqlmodels
from django.db import models
from company.models import Company
from django.contrib.auth.models import User
from financial.models import Currency
# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=80)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    default_tax_rate = models.FloatField()

    class Meta:
        models.Index(fields=["name",])
        ordering = ['name']

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    default_price = models.FloatField()
    price_currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    internal_id = models.IntegerField(null=True)

    class Meta:
        models.Index(fields=["name",])
        ordering = ['-id']

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

invoicing/products/forms.py
from django import forms
from .models import Product
from .models import ProductCategory


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "category", "default_price", "price_currency", "internal_id"]

    def clean_name(self):
        try:
            name = self.cleaned_data['name']
        except KeyError:
            raise forms.ValidationError("Product name cannot be blank")
        return name

    def clean_category(self):
        try:
            category = self.cleaned_data['category']
        except KeyError:
            raise forms.ValidationError("Category cannot be blank")
        db_category = category
        if not db_category.id:
            raise forms.ValidationError("Category does not exist")
        return category

    def clean_default_price(self):
        try:
            default_price = self.cleaned_data['default_price']
        except KeyError:
            return None

        if default_price < 0:
            raise forms.ValidationError("Default price cannot be lower than 0!")
        return default_price

    def clean_price_currency(self):
        try:
            price_currency = self.cleaned_data['price_currency']
        except KeyError:
            raise forms.ValidationError("Currency for default price is mandatory")
        return price_currency

    def save(self, *args, **kwargs):
        self.instance.company = kwargs.pop('company')
        super(ProductForm, self).save(*args, **kwargs)


class ProductCategoryForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ['name', 'default_tax_rate']

    def clean_default_tax_rate(self):
        try:
            tax_rate = self.cleaned_data['default_tax_rate']
        except KeyError:
            raise forms.ValidationError("Default tax rate is mandatory")

        try:
            tax_rate = float(tax_rate)
        except:
            raise forms.ValidationError("Tax rate must be a number")

        if tax_rate < 0:
            raise forms.ValidationError("Tax rate cannot be negative!")
        return tax_rate

    def save(self, *args, **kwargs):
        self.instance.company = kwargs.pop('company')
        super(ProductCategoryForm, self).save(*args, **kwargs)

invoicing/products/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404, Http404, redirect
from .forms import ProductCategoryForm, ProductForm
from django.contrib import messages
from django.db import transaction
from django.views.decorators.cache import cache_page
from core.cache.decorators import cache_per_param


class ProductsListView(View):
    @method_decorator(login_required)
    def get(self, request):
        categories = ProductCategory.objects.select_related().filter(company=request.user.profile.company)
        return render(request, template_name="product/list.html", context={'categories': categories})

class AddProductView(View):
    @method_decorator(login_required)
    @method_decorator(cache_page(60 * 60))
    @method_decorator(cache_per_param(cache_per_user=True, param="id", prefix="add_product"))
    def get(self, request):
        form = ProductForm()
        form.fields['category'].queryset = ProductCategory.objects.filter(company=request.user.profile.company)
        return render(request, template_name="product/add.html", context={'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = ProductForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data['category']
            if category.company != request.user.profile.company:
                raise Http404("The category does not belong to your company")

            with transaction.atomic():
                sid = transaction.savepoint()
                form.save(company=request.user.profile.company)

        else:
            return self.fail_request(request, form)

        messages.add_message(request, messages.SUCCESS, "Product added succesfully!")
        return redirect('product_list')

    def fail_request(self, request, form, exception=None):
        if Exception is not None:
            messages.add_message(request, messages.ERROR, exception)
        for error in form.errors:
            messages.add_message(request, messages.ERROR, error)
        return render(request, template_name='product/add_category.html', context={'form': form}, status=404)


class ProductCategoryView(View):
    @method_decorator(login_required)
    def get(self, request, id):
        product_category = get_object_or_404(ProductCategory, id=id)
        if product_category.company != request.user.profile.company:
            raise Http404
        return render(request, template_name="product/category.html",
                      context={'category': product_category})


class ProductCategoryEditView(View):
    @method_decorator(login_required)
    def get(self, request):
        try:
            id = request.GET['id']
            product_category = get_object_or_404(ProductCategory, pk=id)
            if product_category.company != request.user.profile.company:
                raise Http404
        except KeyError:
            product_category = None

        form = ProductCategoryForm(instance=product_category)
        return render(request, template_name='product/add_category.html', context={'form' : form})
    @method_decorator(login_required)
    def post(self, request):
        form = ProductCategoryForm(request.POST)
        if form.is_valid():
            try:
                id = request.GET['id']
                if id:
                    category = get_object_or_404(ProductCategory, pk=id)
                    if category.company != request.user.profile.company:
                        raise Http404

            except KeyError:
                category = False
            if category:
                category.update()
            else:
                with transaction.atomic():
                    try:
                        sid = transaction.savepoint()
                        form.save(company=request.user.profile.company, commit=True)
                        transaction.savepoint_commit(sid)
                    except Exception as e:
                        transaction.rollback(sid)
                        return self.fail_request(request, form, exception=e)
                messages.add_message(request,messages.SUCCESS, "Category added succesfully!" )
                return redirect('product_list')
        else:
            return self.fail_request(request, form)

    def fail_request(self, request, form, exception=None):
        if Exception is not None:
            messages.add_message(request, messages.ERROR, exception)
        for error in form.errors:
            messages.add_message(request, messages.ERROR, error)
        return render(request, template_name='product/add_category.html', context={'form': form}, status=404)

invoicing/templates/product/add.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
</div>
<div class="row align-items-center" style="margin:auto; padding:70px 0;">
<div class="card mx-auto mr-auto justify-content-center" style="width: 18rem;">
    <div class="card-header">
        <h1 class="card-title">Add new Product</h1>
    </div>
        <div class="card-body">
            <div class="wrapper">
        <form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">

</form>
            </div>
</div>
</div>
</div>
{% endblock %}

invoicing/templates/product/add_category.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
</div>
<div class="row align-items-center" style="margin:auto; padding:70px 0;">
<div class="card mx-auto mr-auto justify-content-center" style="width: 18rem;">
    <div class="card-header">
        <h1 class="card-title">Add new category</h1>
    </div>
        <div class="card-body">
            <div class="wrapper">
        <form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">

</form>
            </div>
</div>
</div>
</div>
{% endblock %}

invoicing/templates/product/category.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
</div>
<div class="row align-items-center" style="margin:auto; padding:70px 0;">
<div class="card mx-auto mr-auto justify-content-center" style="width: 18rem;">
    <div class="card-header">
        <h1 class="card-title">{{category.name}}</h1>
    </div>
        <div class="card-body">
            <div class="wrapper">
                <row class="col-md-3">Name: {{category.name}}</row>
                <row class="col-md-3">Default Tax rate: {{category.default_tax_rate}}</row>
                <row><a href="{% url  %}"</row>
            </div>

</div>
</div>
</div>
{% endblock %}

invoicing/templates/product/list.html
{% extends 'base.html' %}

{% block content %}
<H1>Products</H1>
<a class='btn' href="{% url 'add_product' %}">Add New</a>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Default Price</th>
        <th scope="col">Price Currency</th>
        <th scope="col">Action</th>
    </tr>
  </thead>

{% for category in categories %}
    <tr>
        <td colspan="3"><b>Category: {{category.name}}</b></td>
    <td colspan="2"><b>Tax Rate(%):{{category.default_tax_rate}}</b></td></tr>
    {% for product in category.product_set.all %}
    <tr>
        <td>{{product.id}}</td>
        <td>{{product.name}}</td>
        <td>{{product.default_price}}</td>
        <td>{{product.price_currency}}</td>

      <td></td>
    </tr>
    {% endfor %}
    {% endfor %}
</table>
<a href="{%url 'add_product_category'%}">Add new category</a>
{% endblock %}