invoicing/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import MakeOrderView, InvoiceView, InvoiceListView, UsersView, CreateUserView, ListProductsView
from rest_framework.authtoken import views
urlpatterns = [
  url(r'^invoice/$', InvoiceListView.as_view()),
  url(r'invoice/(?P<id>\d+)/$', InvoiceView.as_view()),
  url(r'users/$', UsersView.as_view()),
  url(r'users/create$', CreateUserView.as_view()),
  url(r'company/(?P<company_id>\d+)/products$', ListProductsView.as_view()),
  url(r'orders/create', MakeOrderView.as_view()),
]

urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token)
]
urlpatterns = format_suffix_patterns(urlpatterns)

invoicing/invoicing/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import index


#delete on going live
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Pastebin API')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('invoice/', include('invoice.urls')),
    path('', index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('company/', include('company.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^docs/', schema_view),
    path('api/', include("api.urls")),
    path('products/', include("products.urls")),
    path('orders/', include("orders.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



#delete when going to prod, static files have to be served on media server, memcached


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

from django.conf.urls import handler400, handler403, handler404, handler500


handler400 = 'invoicing.views.bad_request'
handler403 = 'invoicing.views.permission_denied'
handler404 = 'invoicing.views.page_not_found'
handler500 = 'invoicing.views.server_error'

invoicing/products/models.py
#from django_mysql import models as mysqlmodels
from django.db import models
from company.models import Company
from django.contrib.auth.models import User
from financial.models import Currency
# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=80)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    default_tax_rate = models.FloatField()

    class Meta:
        models.Index(fields=["name",])
        ordering = ['name']

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    default_price = models.FloatField()
    price_currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    internal_id = models.IntegerField(null=True)

    class Meta:
        models.Index(fields=["name",])
        ordering = ['-id']

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

invoicing/templates/401.html
{% extends 'index.html' %}

{% block content %}
<h1>You don't have access to see this page</h1>
{% endblock %}

invoicing/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'invoicing/css/style.css' %}" />
    <meta charset="UTF-8">
     <link rel="stylesheet" type="text/css" href="{% static 'invoicing/css/bootstrap.min.css' %}" />
    <script type="text/javascript"  src="{% static 'invoice/js/jquery-3.2.1.slim.min.js' %}"></script>
    <script type="text/javascript"  src="{% static 'invoice/js/popper.min.js' %}"></script>
   <script type="text/javascript"  src="{% static 'invoice/js/bootstrap.min.js' %}"></script>
    {% block title %}
    {% endblock %}
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="nav navbar navbar-default navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      {% if user.is_authenticated %}
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'customers' %}">Customers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'product_list' %}">Products</a>
      </li>
              <li class="nav-item">
        <a class="nav-link" href="{% url 'list_orders' %}">Orders</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Invoices
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'new_invoice' %}">New</a>
          <a class="dropdown-item" href="{% url 'invoices_issued' %}">Issued</a>
          <a class="dropdown-item" href="{% url 'invoices_received' %}">Received</a>
        </div>
      </li>
        {% endif %}
    </ul>


  </div>
<div class="float-right">

    {% if user.is_authenticated %}
    <a href="{% url 'profile_view' user.id %}">{{user.first_name}}</a>
          <a href="{% url 'logout' %}">
        <button class="btn btn-link">Log out</button>
    </a>
    {% else %}
    <a href="{% url 'login' %}">
        <button class="btn btn-link">Log In</button>
    </a>
    {% endif %}


</div>

  </nav>

<main class="container" role="main">
    {% if messages %}
    {% for message in messages %}
        <div class="{{message.tags}}">{{message}}</div>
    {% endfor %}
    {% endif %}
{% block content %}
{% endblock %}
</main>
<footer class="footer bg-light sticky-bottom">
    <div class="container">
            <span class="text-muted">This software is published under <a href="http://www.wtfpl.net/"> WTFPL license</a>.</p><p>&copy Juan Castillo & Jakub Dering</p></span>
        </div>
</footer>
</body>
</html>